src/Entity/ModeleDocument.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;


/**
 * @ORM\Entity(repositoryClass="App\Repository\ModeleDocumentRepository")
 */
class ModeleDocument
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $certificatMedical;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $droitImage;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $droitTransport;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $droitPratique;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $droitEntrainement;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $RenseignementsMedicaux;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $renseignementsGeneraux;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $reglement;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $statuts;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCertificatMedical()
    {
        return $this->certificatMedical;
    }

    public function setCertificatMedical($certificatMedical)
    {
        $this->certificatMedical = $certificatMedical;

        return $this;
    }

    public function getDroitImage()
    {
        return $this->droitImage;
    }

    public function setDroitImage($droitImage)
    {
        $this->droitImage = $droitImage;

        return $this;
    }

    public function getDroitTransport()
    {
        return $this->droitTransport;
    }

    public function setDroitTransport($droitTransport)
    {
        $this->droitTransport = $droitTransport;

        return $this;
    }

    public function getDroitPratique()
    {
        return $this->droitPratique;
    }

    public function setDroitPratique($droitPratique)
    {
        $this->droitPratique = $droitPratique;

        return $this;
    }

    public function getDroitEntrainement()
    {
        return $this->droitEntrainement;
    }

    public function setDroitEntrainement($droitEntrainement)
    {
        $this->droitEntrainement = $droitEntrainement;

        return $this;
    }

    public function getRenseignementsMedicaux()
    {
        return $this->RenseignementsMedicaux;
    }

    public function setRenseignementsMedicaux($RenseignementsMedicaux)
    {
        $this->RenseignementsMedicaux = $RenseignementsMedicaux;

        return $this;
    }

    public function getRenseignementsGeneraux()
    {
        return $this->renseignementsGeneraux;
    }

    public function setRenseignementsGeneraux($renseignementsGeneraux)
    {
        $this->renseignementsGeneraux = $renseignementsGeneraux;

        return $this;
    }

    public function getReglement()
    {
        return $this->reglement;
    }

    public function setReglement($reglement)
    {
        $this->reglement = $reglement;

        return $this;
    }

    public function getStatuts()
    {
        return $this->statuts;
    }

    public function setStatuts($statuts)
    {
        $this->statuts = $statuts;

        return $this;
    }
}

src/Controller/WebsiteController.php
<?php

namespace App\Controller;

use App\Entity\Evenement;
use App\Form\ContactType;
use App\Entity\TexteAccueil;
use App\Entity\Participation;
use App\Form\EditAdherentType;
use App\Entity\DossierInscription;
use App\Service\PaginationService;
use App\Form\DossierInscriptionType;
use App\Entity\ParticipationEvenement;
use App\Repository\AdherentRepository;
use App\Repository\EvenementRepository;
use App\Repository\TexteAccueilRepository;
use Knp\Component\Pager\PaginatorInterface;
use App\Repository\ModeleDocumentRepository;
use App\Repository\CarouselPictureRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use App\Repository\TexteFooterContactRepository;
use App\Repository\ParticipationEvenementRepository;
use App\Repository\TextePresentationEcoleRepository;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface;

class WebsiteController extends AbstractController

{
    /**
     * @Route("/", name="home")
     */

    public function index(EvenementRepository $repo, TexteFooterContactRepository $footer, CarouselPictureRepository $carousel, TexteAccueilRepository $repotexte)
    {
        $evenements = $repo->findUpcomingEvents();
        $texte = $repotexte->findAll();

        return $this->render('home/home.html.twig', [
            'evenements' => $evenements,
            'picture'=>$carousel->findAll(),
            'textes' => $texte
        ]);
    }

    /**
     * @Route("/evenements/{page<\d+>?1}", name="evenements")
     */
    public function listeEvenements($page, PaginationService $pagination, EvenementRepository $repo, TokenStorageInterface $tokenStorage)
    {
        $pagination->setEntityClass(Evenement::class)
                   ->setPage($page);

        $user=$tokenStorage->getToken()->getUser();

        return $this->render('event/events.html.twig', [
            'pagination' => $pagination,
            'user' => $user
        ]);
    }

    /**
     * Permet d'afficher un seul événement
     * @Route("/visiteur/evenements/{id}", name="detailevenementvisiteur")
     * 
     * @return Response
     */

    public function detailEvenements($id, EvenementRepository $repo)
    {
        $evenement = $repo->findAll();
        $evenement = $repo->find($id);
        $manager = $this->getDoctrine()->getManager();
            return $this->render('visiteur/visiteur_detailEvenements.html.twig', [
                'evenement' => $evenement,
                'id' => $id
            ]);
    }

    /**
     * Permet d'afficher un seul événement
     * @Route("/contact", name="contact")
     * 
     */
    public function pageContact(Request $request, \Swift_Mailer $mailer, TexteFooterContactRepository $repo)
    {
        $form = $this->createForm(ContactType::class);
        $contacts = $repo->findAll();

            $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $contactFormData = $form->getData();
            $message = (new \Swift_Message('Nouveau message du site'))
                ->setFrom($contactFormData['from'])
                ->setTo('raseteur.test@gmail.com')
                ->setBody(
                    $contactFormData['message'],
                    'text/plain'
                );

                $mailer->send($message);
            $this->addFlash('success', 'Merci, votre message a bien été envoyé');
            return $this->redirectToRoute('home');
        }
        
            return $this->render('website/contact.html.twig', [
            'form' => $form->createView(),
            'contacts' => $contacts
            ]);
    }

    /**
      * Afficher les documents viérges pour l'inscription
     * @Route("/dossier/vierge", name="dossier_inscription_vierge")
     */
    public function fileInsciption(ModeleDocumentRepository $modeleDocumentRepository)
    {
    
        return $this->render('website/dossierInscriptionVierge.html.twig',[
            'documentModele'=> $modeleDocumentRepository->findAll()
        ]);
         
    }
    
    /**
     * Permet d'afficher un seul événement
     * @Route("/ecole", name="ecole")
     * 
     * @return Response
     */
    public function pageEcole(TextePresentationEcoleRepository $repositorypresentation)
    {
        $contenuEcole = $repositorypresentation->findAll();

            return $this->render('website/ecole.html.twig', [
            'textes' => $contenuEcole
            ]);
    }
    

    /**
     * @Route("/footer", name="footer")
     */
    public function footer(TexteFooterContactRepository $repo)
    {
        $adresse = $repo->findOneBy(array('id' => 3))->getAdresse();
        $contacts = $repo->findAll();
        
        return $this->render('footer/index.html.twig', [
            'adresse' => $adresse,
            'contacts' => $contacts
        ]);
    }
     
}

templates/website/adherentEditProfile.html.twig
{% extends "base.html.twig" %} {% block body %}
<div class="content ">
  <div class="row justify-content-center">
    <div>
      <h3 class="text-center">MODIFIER VOS INFORMATIONS PERSONNELLES</h3>
      <hr />
    </div>
  </div>

  <div class="row justify-content-center">
    <div class="card text-white shadow-lg bg-primary col-5">
      <div class="card-body ">
        <div class="card-content">
          {{ form_start(adherent) }}
          <h5 class="text-center">Informations personnelles</h5>
          {{form_row(adherent.nom,{'attr':{'placeholder':""}})}}
          {{form_row(adherent.prenom,{'attr':{'placeholder':""}})}}
          {{form_row(adherent.telephone,{'attr':{'placeholder':""}})}}
          {{form_row(adherent.adresse,{'attr':{'placeholder':""}})}}
          {{form_row(adherent.cp,{'attr':{'placeholder':""}})}}
          {{form_row(adherent.ville,{'attr':{'placeholder':""}})}}
          {{form_row(adherent.numeroUrgence,{'attr':{'placeholder':""}})}}
          {{form_row(adherent.nomUrgence,{'attr':{'placeholder':""}})}}
          <h5 class="text-center">Securité</h5>
          {{form_row(adherent.email,{'attr':{'placeholder':""}})}}
          {{ form_row(adherent.password.first,{'attr':{'class':"hidden-row"}})}}
          {{ form_row(adherent.password.second) }}
          <div class="text-center pt-3">
            <button type="submit" class="btn btn-success mb-1">
              Modification
            </button>
            {{ form_end(adherent) }}
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/website/contact.html.twig
{% extends 'base.html.twig' %} {% block title %}Contactez-nous {% endblock %} {%
block body %}

<div class="container-fluid">
  <div class="container">
    <div class="row">
      <div class="col-6">
        <h3>
          Formulaire de contact
        </h3>

        {{ form_start(form) }}
        {{ form_widget(form) }}
        {{ form_end(form) }}
      </div>

      <div class="col-6 justify-text-center">
        <h3 class="mt-1">
          Nos coordonnées
        </h3>

        {% for contact in contacts %}

        <h4 class="titlecontact">{{ contact.nom }}</h4>
        <br />

        <p>
          Pour tout renseignement, vous pouvez nous contacter via la page
          Facebook, ou par téléphone. Notre formulaire de contact reste à votre
          disposition, nous vous répondrons dans les plus brefs délais.
        </p>

        <i class="fas fa-map-marker-alt"></i>

        {{ contact.adresse }}
        -
        {{ contact.cp }}
        -
        {{ contact.ville }}<br />
        <i class="fas fa-phone-alt"></i>
        {{ contact.telephone1 }}<br />
        <br />

        <h4 class="titlecontact">Lieux d'entraînement</h4>
        <br />

        <div class="row">
          <div class="col-6">
            <img src="/img/entressens.png" width=" 300" height=" 300" />
          </div>

          <div class="col-6">
            <img class="pl-4" src="/img/miramas.png" width="300" height="300" />
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>

{% endblock %}

templates/website/dossierInscriptionVierge.html.twig
{% extends 'base.html.twig' %}
{% block title %}
- Dossier d'inscription
{% endblock %}
{% block body %}
<div class="container">

    {% if documentModele %}
    
    <div class="row justify-content-center mt-3">
        <div class=" mt-3 p-3 mb-2 bg-white rounded p-center">
            <div>
                <h3>DOCUMENTs D'INSCRIPTION </h3>
            </div>
            <hr>
        </div>
    </div>
    
    <div class="alert alert-danger alert-dismissible fade show mb-5" role="alert">
        <h4 class="alert-heading">Message important !</h4>
        <p>
            Il faut étre pre-inscrit sur le site avant de pouvoir s'inscrire à notre association</p>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="row offset-2 mt5" >
        <div class="col justify-content-center">
            <h5><a class="doc" href="{{ asset('uploads/documentsModele/' ~ documentModele.0.CertificatMedical) }}"><img src="https://img.icons8.com/office/80/000000/folder-invoices.png"></a>Certificat medical(PDF)</h5>
        </div>
        <div class="col justify-content-center">
            <h5><a class="doc" href="{{ asset('uploads/documentsModele/' ~ documentModele.0.DroitImage) }}"><img src="https://img.icons8.com/office/80/000000/folder-invoices.png"></a>Droit d'image(PDF)</h5>
        </div>
    </div>
    <div class="row offset-2">
        <div class="col justify-content-center">
            <h5><a class="doc" href="{{ asset('uploads/documentsModele/' ~ documentModele.0.droitTransport) }}"><img src="https://img.icons8.com/office/80/000000/folder-invoices.png"></a>Droit transport(PDF)</h5>
        </div>
        <div class="col justify-content-center">
            <h5><a class="doc" href="{{ asset('uploads/documentsModele/' ~ documentModele.0.droitPratique) }}"><img src="https://img.icons8.com/office/80/000000/folder-invoices.png"></a>Droit pratique(PDF)</h5>
        </div>
    </div>
    <div class="row offset-2">
        <div class="col justify-content-center">
            <h5><a class="doc" href="{{ asset('uploads/documentsModele/' ~ documentModele.0.droitEntrainement) }}"><img src="https://img.icons8.com/office/80/000000/folder-invoices.png"></a>Droit d'entrainement(PDF)</h5>
        </div>
        <div class="col justify-content-center">
            <h5><a class="doc" href="{{ asset('uploads/documentsModele/' ~ documentModele.0.renseignementsMedicaux) }}"><img src="https://img.icons8.com/office/80/000000/folder-invoices.png"></a>Renseignements médicaux(PDF)</h5>
        </div>
    </div>
    <div class="row offset-2 mb-5">
        <div class="col justify-content-center">
            <h5><a class="doc" href="{{ asset('uploads/documentsModele/' ~ documentModele.0.renseignementsgeneraux) }}"><img src="https://img.icons8.com/office/80/000000/folder-invoices.png"></a>Renseignements Generaux(PDF)</h5>
        </div>
        <div class="col justify-content-center">
            <h5><a class="doc" href="http://www.ffcc.info/336-reglement_de_la_competition_2019-5.html"><img src="https://img.icons8.com/office/80/000000/folder-invoices.png"></a>Réglement de la FFCC (à telecharger)</h5>
        </div>
    </div>

    {% else %}
        <!-- Si les documents vierge sont pas disponible -->
        <div class="row justify-content-center mt-5 mb-5">
            <div class="col-md-12 text-center mt-5 mt-5">
                <span class="display-1 d-block">404</span>
                <div class="mb-4 lead mt-5"> <h3>Cette page est actuellement pas disponible veuillez nous excuser </h3>  </div>
            </div>
        </div>
        <div class="row text-center  mb-5 mt-5" > 
            <div class="col">
                <a href="{{ path('home') }}" type="button" class="btn"> Retourner à l'accueil</a>
              </div>
        </div>
    {% endif %}
</div>
    
{% endblock %}

templates/website/ecole.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	- L'école
{% endblock %}

{% block body %}

	<div class="container">

	
		{% for texte in textes %}
		<div
			class="jumbotron">
			<!-- section -->
			<div class="container bg-2 text-center">

			
				<h3>{{ texte.titre }}</h3>
		

				{% if texte.photo %}

				<img src="{{ asset('uploads/photoSection/' ~ texte.photo ) }} " width="300em" height="300em">

				{% else %}
				{% endif %}

				{{ texte.section }}

		
			</div>
		</div>
		​
		​{% endfor %}
		<h4>Documents à télécharger</h4>

				Afin de télécharger les différents documents nécessaires pour l'inscription à l'école, cliquez <a href="{{ path('dossier_inscription_vierge') }} ">ici</a>
	</div>

{% endblock %}